import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { createClient } from "@/lib/supabase/server";

// GET /api/obreros — list obreros for this contratista
export async function GET() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser();
    if (error || !user) {
      return NextResponse.json({ error: "No autorizado" }, { status: 401 });
    }

    const usuario = await prisma.usuario.findUnique({
      where: { email: user.email! },
      select: {
        id: true,
        constructora_id: true,
        rol_ref: { select: { nivel_acceso: true } },
      },
    });

    if (!usuario) {
      return NextResponse.json(
        { error: "Usuario no encontrado" },
        { status: 404 }
      );
    }

    if (usuario.rol_ref.nivel_acceso !== "CONTRATISTA") {
      return NextResponse.json(
        { error: "Solo contratistas pueden gestionar obreros" },
        { status: 403 }
      );
    }

    const obreros = await prisma.obrero.findMany({
      where: { contratista_id: usuario.id },
      orderBy: { created_at: "desc" },
      select: {
        id: true,
        nombre: true,
        token: true,
        activo: true,
        fecha_inicio: true,
        fecha_expiracion: true,
        created_at: true,
        _count: { select: { evidencias: true } },
      },
    });

    return NextResponse.json(obreros);
  } catch (error) {
    console.error("GET /api/obreros", error);
    return NextResponse.json({ error: "Error interno" }, { status: 500 });
  }
}

// POST /api/obreros — create a new obrero
export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser();
    if (error || !user) {
      return NextResponse.json({ error: "No autorizado" }, { status: 401 });
    }

    const usuario = await prisma.usuario.findUnique({
      where: { email: user.email! },
      select: {
        id: true,
        constructora_id: true,
        rol_ref: { select: { nivel_acceso: true } },
      },
    });

    if (!usuario) {
      return NextResponse.json(
        { error: "Usuario no encontrado" },
        { status: 404 }
      );
    }

    if (usuario.rol_ref.nivel_acceso !== "CONTRATISTA") {
      return NextResponse.json(
        { error: "Solo contratistas pueden crear obreros" },
        { status: 403 }
      );
    }

    const body = await req.json();
    const { nombre, fecha_inicio, fecha_expiracion } = body as {
      nombre?: string;
      fecha_inicio?: string;
      fecha_expiracion?: string;
    };

    if (!nombre || !fecha_inicio || !fecha_expiracion) {
      return NextResponse.json(
        { error: "nombre, fecha_inicio y fecha_expiracion son requeridos" },
        { status: 400 }
      );
    }

    const trimmedNombre = nombre.trim();
    if (trimmedNombre.length < 2 || trimmedNombre.length > 100) {
      return NextResponse.json(
        { error: "El nombre debe tener entre 2 y 100 caracteres" },
        { status: 400 }
      );
    }

    const inicio = new Date(fecha_inicio);
    const expiracion = new Date(fecha_expiracion);

    if (isNaN(inicio.getTime()) || isNaN(expiracion.getTime())) {
      return NextResponse.json(
        { error: "Fechas invalidas" },
        { status: 400 }
      );
    }

    if (expiracion <= inicio) {
      return NextResponse.json(
        { error: "La fecha de expiracion debe ser posterior a la de inicio" },
        { status: 400 }
      );
    }

    // Token is auto-generated by Prisma schema (@default(cuid()))
    const obrero = await prisma.obrero.create({
      data: {
        nombre: trimmedNombre,
        contratista_id: usuario.id,
        constructora_id: usuario.constructora_id,
        fecha_inicio: inicio,
        fecha_expiracion: expiracion,
      },
      select: {
        id: true,
        nombre: true,
        token: true,
        activo: true,
        fecha_inicio: true,
        fecha_expiracion: true,
        created_at: true,
      },
    });

    // Build full URL
    const siteUrl =
      process.env.NEXT_PUBLIC_SITE_URL ?? "https://seiricon.com";
    const url = `${siteUrl}/o/${obrero.token}`;

    return NextResponse.json({ ...obrero, url }, { status: 201 });
  } catch (error) {
    console.error("POST /api/obreros", error);
    return NextResponse.json({ error: "Error interno" }, { status: 500 });
  }
}
