-- Add SUPER_ADMIN to NivelAcceso enum.
-- Mantenemos la jerarquía: SUPER_ADMIN > DIRECTIVO > ADMIN_GENERAL > ADMIN_PROYECTO > CONTRATISTA > OBRERO
ALTER TYPE "NivelAcceso" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
